# Generated by Django 3.0.5 on 2020-08-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='p_name',
            new_name='c_name',
        ),
    ]
