# Generated by Django 3.0.5 on 2020-08-24 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_auto_20200824_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
