# Generated by Django 3.0.5 on 2020-08-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_placeorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeorder',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
