# Generated by Django 3.0.5 on 2020-08-26 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
