# Generated by Django 3.0.5 on 2020-08-13 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('length', models.IntegerField()),
                ('singer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
